// ================== 角色档案 (Character) JS ==================
// 本文件包含角色档案页面（#character-page）及角色管理的所有 JS 逻辑
// 依赖：db, showToast 等全局变量（来自 script.js）
// --- 角色档案 (Character) 逻辑 ---
function showCharacterPage() {
    document.getElementById('character-page').style.display = 'flex';
    loadCharacterList();
}

        function hideCharacterPage() {
            const page = document.getElementById('character-page');
            page.style.transform = 'scale(0.95)';
            page.style.opacity = '0';
            setTimeout(() => {
                page.style.display = 'none';
                page.style.transform = ''; 
                page.style.opacity = '';
            }, 200);
        }

        function switchCharacterTab(type) {
            currentCharacterType = type;
            
            // 更新底部样式
            ['char', 'npc', 'user'].forEach(t => {
                const el = document.getElementById(`tab-${t}`);
                if (t === type) {
                    el.style.color = 'var(--ins-pink)';
                } else {
                    el.style.color = '#999';
                }
            });
            
            loadCharacterList();
        }

        async function loadCharacterList() {
            const container = document.getElementById('character-list');
            container.innerHTML = '';
            
            // 从数据库获取指定类型的角色
            const list = await db.characters.where('type').equals(currentCharacterType).toArray();
            
            if (list.length === 0) {
                container.innerHTML = `
                    <div style="grid-column: span 2; text-align:center; color:#999; margin-top:60px; display:flex; flex-direction:column; align-items:center; gap:10px;">
                        <svg class="svg-icon" style="width:40px; height:40px; stroke:#ccc;" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"></circle><line x1="8" y1="15" x2="16" y2="15"></line><line x1="9" y1="9" x2="9.01" y2="9"></line><line x1="15" y1="9" x2="15.01" y2="9"></line></svg>
                        <div>这里还没人哦</div>
                    </div>
                `;
                return;
            }

            list.forEach(char => {
                const div = document.createElement('div');
                div.className = 'char-card';
                div.onclick = () => editCharacter(char.id);
                
                // 默认头像（按账号隔离）
                const _cardAv = getCharAvatar(char, getCurrentAccountId());
                let bgStyle = 'background-color: #eee;';
                if (_cardAv) {
                    bgStyle = `background-image: url(${_cardAv});`;
                }
                
                div.innerHTML = `
                    <div class="char-card-img" style="${bgStyle}"></div>
                    <div class="char-card-info">
                        <div class="char-name">${char.name || '未命名'}</div>
                        <div class="char-nick">${char.nick || ''}</div>
                    </div>
                `;
                container.appendChild(div);
            });
        }

        function createNewCharacter() {
            editingCharId = null;
            document.getElementById('char-editor-title').innerText = "新建角色";
            document.getElementById('char-name').value = '';
            document.getElementById('char-nick').value = '';
            document.getElementById('char-desc').value = '';
            document.getElementById('char-type').value = currentCharacterType; // 默认选中当前 Tab 类型
            document.getElementById('char-avatar-preview').style.backgroundImage = '';
            document.getElementById('char-avatar-placeholder').style.display = 'flex';
            
            // 隐藏NPC编辑提示
            const descHint = document.getElementById('char-desc-hint');
            if (descHint) descHint.style.display = 'none';
            
            // 🎯 自动生成手机号（前7位固定 1380000，后4位随机）
            const autoGeneratedPhone = generateRandomPhone();
            console.log('[创建角色] 自动生成手机号:', autoGeneratedPhone);
            
            // 清空虚拟身份信息
            document.getElementById('char-identity-account').value = '';
            document.getElementById('char-identity-password').value = '';
            document.getElementById('char-identity-phone').value = autoGeneratedPhone; // 自动填充手机号
            document.getElementById('char-identity-address').value = '';
            document.getElementById('char-identity-id').value = '';
            document.getElementById('char-identity-bank').value = '';
            document.getElementById('char-identity-bank-pass').value = '';

            document.getElementById('character-editor-page').style.display = 'flex';
            
            // 🎉 显示手机号分配弹窗
            setTimeout(() => {
                showPhoneAssignedModal(autoGeneratedPhone);
            }, 300); // 稍微延迟，等待编辑器页面打开
        }

        async function editCharacter(id) {
            editingCharId = id;
            const char = await db.characters.get(id);
            if (!char) return;
            
            document.getElementById('char-editor-title').innerText = "编辑角色";
            document.getElementById('char-name').value = char.name || '';
            document.getElementById('char-nick').value = char.nick || '';
            document.getElementById('char-desc').value = char.description || '';
            document.getElementById('char-type').value = char.type || 'char';
            
            // 如果是NPC且有描述，显示提示
            const descHint = document.getElementById('char-desc-hint');
            if (char.type === 'npc' && char.description) {
                descHint.style.display = 'block';
            } else {
                descHint.style.display = 'none';
            }
            
            // 回显虚拟身份信息
            const idData = char.identity || {};
            document.getElementById('char-identity-account').value = idData.account || '';
            document.getElementById('char-identity-password').value = idData.password || '';
            document.getElementById('char-identity-phone').value = idData.phone || '';
            document.getElementById('char-identity-address').value = idData.address || '';
            document.getElementById('char-identity-id').value = idData.id_card || '';
            document.getElementById('char-identity-bank').value = idData.bank_card || '';
            document.getElementById('char-identity-bank-pass').value = idData.bank_password || '';

            // ✅ 档案头像使用基础头像(char.avatar)，不受 WeChat 换头像影响
            const _editAv = char.avatar || '';
            if (_editAv) {
                document.getElementById('char-avatar-preview').style.backgroundImage = `url(${_editAv})`;
                document.getElementById('char-avatar-placeholder').style.display = 'none';
            } else {
                document.getElementById('char-avatar-preview').style.backgroundImage = '';
                document.getElementById('char-avatar-placeholder').style.display = 'flex';
            }
            
            // 渲染关系列表
            renderRelationList(char);

            document.getElementById('character-editor-page').style.display = 'flex';
        }

        // 渲染编辑页的关系列表
        async function renderRelationList(char) {
            const container = document.getElementById('char-relation-list');
            container.innerHTML = '';
            
            if (!char.relationships || char.relationships.length === 0) {
                container.innerHTML = '<div style="text-align:center; color:#ccc; font-size:12px; padding:10px;">暂无关系记录，点击「添加关系」开始构建人际关系网</div>';
                return;
            }

            // relationships: [{ targetId, targetName, relation, desc }]
            for (let i = 0; i < char.relationships.length; i++) {
                const rel = char.relationships[i];
                // 尝试获取最新的头像
                let avatarUrl = '';
                if (rel.targetId) {
                    const target = await db.characters.get(rel.targetId);
                    if (target && target.avatar) avatarUrl = target.avatar;
                }
                
                const item = document.createElement('div');
                item.className = 'relation-item';
                item.innerHTML = `
                    <div class="relation-avatar" style="${avatarUrl ? `background-image:url(${avatarUrl})` : ''}"></div>
                    <div class="relation-info">
                        <div class="relation-name">${rel.targetName} <span class="relation-tag">${rel.relation}</span></div>
                        <div class="relation-desc">${rel.desc || ''}</div>
                    </div>
                    <div class="relation-actions">
                        <button title="编辑关系" onclick="editRelation(${i})">✏️</button>
                        <button title="删除关系" onclick="deleteRelation(${i})" style="color:#ff3b30;">✕</button>
                    </div>
                `;
                container.appendChild(item);
            }
        }

        // ========== 手动添加/编辑/删除关系 ==========
        let _relationEditIndex = -1; // 编辑模式下的索引，-1表示新增

        // 显示添加关系弹窗
        async function showAddRelationModal() {
            if (!editingCharId) {
                alert("请先保存当前角色后再添加关系");
                return;
            }
            _relationEditIndex = -1;
            
            // 重置表单
            document.getElementById('relation-type-custom').value = '';
            document.getElementById('relation-desc-input').value = '';
            document.getElementById('relation-reverse-type').value = '';
            document.getElementById('relation-bidirectional').checked = true;
            document.getElementById('relation-reverse-section').style.display = 'block';
            document.querySelectorAll('.relation-type-tag').forEach(t => t.classList.remove('active'));
            
            // 加载角色下拉列表
            await loadRelationCharSelect();
            
            document.getElementById('add-relation-modal').style.display = 'flex';
        }
        window.showAddRelationModal = showAddRelationModal;

        // 加载角色下拉列表
        async function loadRelationCharSelect(selectedId) {
            const select = document.getElementById('relation-char-select');
            if (!select) return;
            
            const allChars = await db.characters.toArray();
            const currentChar = await db.characters.get(editingCharId);
            const existingIds = (currentChar?.relationships || []).map(r => r.targetId);
            
            // 过滤：排除自己、排除user类型、新增模式下排除已有关系
            const available = allChars.filter(c => {
                if (c.id === editingCharId) return false;
                if (c.type === 'user') return false;
                if (_relationEditIndex === -1 && existingIds.includes(c.id)) return false;
                return true;
            });
            
            select.innerHTML = '<option value="">-- 请选择角色 --</option>';
            
            // 按类型分组：先角色后NPC
            const chars = available.filter(c => c.type === 'char');
            const npcs = available.filter(c => c.type === 'npc');
            const others = available.filter(c => c.type !== 'char' && c.type !== 'npc');
            
            if (chars.length > 0) {
                const group = document.createElement('optgroup');
                group.label = '角色 (Char)';
                chars.forEach(c => {
                    const opt = document.createElement('option');
                    opt.value = c.id;
                    opt.textContent = c.name + (c.nick ? ' (' + c.nick + ')' : '');
                    if (selectedId && c.id === selectedId) opt.selected = true;
                    group.appendChild(opt);
                });
                select.appendChild(group);
            }
            if (npcs.length > 0) {
                const group = document.createElement('optgroup');
                group.label = 'NPC';
                npcs.forEach(c => {
                    const opt = document.createElement('option');
                    opt.value = c.id;
                    opt.textContent = c.name + (c.nick ? ' (' + c.nick + ')' : '');
                    if (selectedId && c.id === selectedId) opt.selected = true;
                    group.appendChild(opt);
                });
                select.appendChild(group);
            }
            if (others.length > 0) {
                const group = document.createElement('optgroup');
                group.label = '其他';
                others.forEach(c => {
                    const opt = document.createElement('option');
                    opt.value = c.id;
                    opt.textContent = c.name + (c.nick ? ' (' + c.nick + ')' : '');
                    if (selectedId && c.id === selectedId) opt.selected = true;
                    group.appendChild(opt);
                });
                select.appendChild(group);
            }
        }

        // 选择关系类型标签
        function selectRelationType(el, type) {
            document.querySelectorAll('.relation-type-tag').forEach(t => t.classList.remove('active'));
            el.classList.add('active');
            el.dataset.relation = type;
            document.getElementById('relation-type-custom').value = '';
            
            // 自动填充反向关系
            document.getElementById('relation-reverse-type').value = getDefaultReverseRelation(type);
        }
        window.selectRelationType = selectRelationType;

        // 获取默认反向关系
        function getDefaultReverseRelation(relation) {
            const reverseMap = {
                '恋人': '恋人',
                '朋友': '朋友',
                '家人': '家人',
                '同事': '同事',
                '同学': '同学',
                '师生': '学生',
                '学生': '师生',
                '老师': '学生',
                '上下级': '下属',
                '下属': '上级',
                '上级': '下属',
                '对手': '对手',
                '暧昧': '暧昧',
                '前任': '前任',
                '仇人': '仇人',
                '陌生人': '陌生人',
                '关联主角': '关联NPC'
            };
            return reverseMap[relation] || relation;
        }

        // 确认添加关系
        async function confirmAddRelation() {
            if (!editingCharId) return;
            
            // 从下拉框获取选中的角色ID
            const selectEl = document.getElementById('relation-char-select');
            const selectedCharId = selectEl ? parseInt(selectEl.value) : null;
            
            if (!selectedCharId) {
                alert('请先选择一个角色');
                return;
            }
            
            // 获取关系类型
            const activeTag = document.querySelector('.relation-type-tag.active');
            const customType = document.getElementById('relation-type-custom').value.trim();
            const relationType = customType || (activeTag ? activeTag.dataset.relation : '');
            
            if (!relationType) {
                alert('请选择或输入关系类型');
                return;
            }
            
            const desc = document.getElementById('relation-desc-input').value.trim();
            const bidirectional = document.getElementById('relation-bidirectional').checked;
            const reverseType = document.getElementById('relation-reverse-type').value.trim() || getDefaultReverseRelation(relationType);
            
            // 获取选中角色信息
            const targetChar = await db.characters.get(selectedCharId);
            if (!targetChar) {
                alert('选中的角色不存在');
                return;
            }
            
            // 获取当前角色
            const currentChar = await db.characters.get(editingCharId);
            if (!currentChar) return;
            
            if (!currentChar.relationships) currentChar.relationships = [];
            
            if (_relationEditIndex >= 0) {
                // 编辑模式：先删除旧的反向关系
                const oldRel = currentChar.relationships[_relationEditIndex];
                if (oldRel && oldRel.targetId) {
                    const oldTarget = await db.characters.get(oldRel.targetId);
                    if (oldTarget && oldTarget.relationships) {
                        oldTarget.relationships = oldTarget.relationships.filter(r => r.targetId !== editingCharId);
                        await safeCharacterPut(oldTarget);
                    }
                }
                // 更新关系
                currentChar.relationships[_relationEditIndex] = {
                    targetId: targetChar.id,
                    targetName: targetChar.name,
                    relation: relationType,
                    desc: desc
                };
            } else {
                // 新增模式：检查是否重复
                const exists = currentChar.relationships.some(r => r.targetId === targetChar.id);
                if (exists) {
                    alert(`已经与 ${targetChar.name} 建立了关系`);
                    return;
                }
                
                currentChar.relationships.push({
                    targetId: targetChar.id,
                    targetName: targetChar.name,
                    relation: relationType,
                    desc: desc
                });
            }
            
            await safeCharacterPut(currentChar);
            
            // 双向关系：在对方的关系列表中也添加
            if (bidirectional) {
                if (!targetChar.relationships) targetChar.relationships = [];
                // 移除旧的指向当前角色的关系（如果有）
                targetChar.relationships = targetChar.relationships.filter(r => r.targetId !== editingCharId);
                // 添加新的反向关系
                targetChar.relationships.push({
                    targetId: currentChar.id,
                    targetName: currentChar.name,
                    relation: reverseType,
                    desc: desc
                });
                await safeCharacterPut(targetChar);
            }
            
            // 刷新关系列表
            renderRelationList(currentChar);
            closeModal('add-relation-modal');
            
            console.log(`[关系] ✅ ${currentChar.name} ↔ ${targetChar.name}: ${relationType}${bidirectional ? ` (双向: ${reverseType})` : ''}`);
        }
        window.confirmAddRelation = confirmAddRelation;

        // 编辑关系
        async function editRelation(index) {
            if (!editingCharId) return;
            const currentChar = await db.characters.get(editingCharId);
            if (!currentChar || !currentChar.relationships || !currentChar.relationships[index]) return;
            
            const rel = currentChar.relationships[index];
            _relationEditIndex = index;
            
            // 设置关系类型标签
            document.querySelectorAll('.relation-type-tag').forEach(t => {
                t.classList.remove('active');
                if (t.dataset.relation === rel.relation) {
                    t.classList.add('active');
                }
            });
            document.getElementById('relation-type-custom').value = '';
            const matchedTag = document.querySelector('.relation-type-tag.active');
            if (!matchedTag) {
                document.getElementById('relation-type-custom').value = rel.relation;
            }
            
            document.getElementById('relation-desc-input').value = rel.desc || '';
            document.getElementById('relation-bidirectional').checked = true;
            document.getElementById('relation-reverse-type').value = getDefaultReverseRelation(rel.relation);
            document.getElementById('relation-reverse-section').style.display = 'block';
            
            // 加载角色下拉并选中当前关系目标
            await loadRelationCharSelect(rel.targetId);
            
            document.getElementById('add-relation-modal').style.display = 'flex';
        }
        window.editRelation = editRelation;

        // 删除关系
        async function deleteRelation(index) {
            if (!editingCharId) return;
            const currentChar = await db.characters.get(editingCharId);
            if (!currentChar || !currentChar.relationships || !currentChar.relationships[index]) return;
            
            const rel = currentChar.relationships[index];
            const confirmDel = confirm(`确定删除与 ${rel.targetName} 的「${rel.relation}」关系吗？`);
            if (!confirmDel) return;
            
            // 同时删除对方的反向关系
            if (rel.targetId) {
                const targetChar = await db.characters.get(rel.targetId);
                if (targetChar && targetChar.relationships) {
                    targetChar.relationships = targetChar.relationships.filter(r => r.targetId !== editingCharId);
                    await safeCharacterPut(targetChar);
                }
            }
            
            // 删除当前角色的关系
            currentChar.relationships.splice(index, 1);
            await safeCharacterPut(currentChar);
            
            // 刷新列表
            renderRelationList(currentChar);
            console.log(`[关系] 🗑️ 已删除 ${currentChar.name} 与 ${rel.targetName} 的关系`);
        }
        window.deleteRelation = deleteRelation;

        // 双向复选框事件
        document.addEventListener('change', function(e) {
            if (e.target && e.target.id === 'relation-bidirectional') {
                document.getElementById('relation-reverse-section').style.display = e.target.checked ? 'block' : 'none';
            }
        });

        // 显示生成 NPC 弹窗
        function showNpcGenModal() {
            if (!editingCharId) {
                alert("请先保存当前角色后再生成关联 NPC");
                return;
            }
            document.getElementById('npc-gen-modal').style.display = 'flex';
        }

        // 执行生成逻辑
        async function doGenerateNpcs() {
            const count = document.getElementById('gen-count-range').value;
            const req = document.getElementById('gen-prompt-req').value.trim();
            const btn = document.getElementById('btn-do-gen');
            
            // 获取源角色信息
            const sourceChar = await db.characters.get(editingCharId);
            if (!sourceChar) return;

            btn.innerText = "生成中...";
            btn.disabled = true;

            try {
                // 1. 构建 Prompt
                let loreContext = "";
                let entriesCount = 0;
                const sourceLorebookIds = sourceChar.lorebookIds || (sourceChar.lorebookId ? [sourceChar.lorebookId] : []);
                if (sourceLorebookIds.length > 0) {
                    // 合并多个世界书的所有词条
                    let allEntries = [];
                    for (const bookId of sourceLorebookIds) {
                        const book = await db.lorebooks.get(bookId);
                        if (book && book.content && book.content.entries) {
                            const bookEntries = Object.values(book.content.entries)
                                .filter(e => e.enabled)
                                .map(e => `[词条: ${e.key}]\n${e.content}`);
                            allEntries = allEntries.concat(bookEntries);
                        }
                    }
                    
                    entriesCount = allEntries.length;
                    if (entriesCount > 0) {
                        // 为了防止Token溢出，按长度截断（假设约 12000 字符为安全区，留给 Response 和 Prompt）
                        const entriesText = allEntries.join('\n\n');
                        loreContext = `【世界观背景 (Lorebook - 共${entriesCount}条设定)】\n${entriesText.slice(0, 12000)}\n`;
                        if (entriesText.length > 12000) loreContext += `\n...(部分设定因过长已省略)`;
                    }
                }

                const prompt = `你是一个专业的TRPG/小说角色设计助手。请根据以下【主角信息】和【世界观背景】，深度创作 ${count} 个相关的 NPC 角色。
${req ? `>>> 特别剧情要求：${req} <<<` : ''}

【主角信息】
名字：${sourceChar.name}
设定：${sourceChar.description}

${loreContext}

【生成要求】
1. **深度关联**：NPC 必须与世界观（Lorebook）紧密结合。请引用世界书中的地名、组织、种族或历史事件。
2. **细节丰富**：请详细描写外貌（衣着、特征）、性格（口癖、心理）和背景故事。拒绝空洞的描述。
3. **多样性**：生成的角色性格和身份应各不相同，除非【特别剧情要求】另有指定。

请返回一个 JSON 数组，每个对象包含：
- name: 名字
- nickname: 昵称 (可选)
- gender: 性别 (男/女/未知)
- appearance: 外貌描写 (详细，如发色、瞳色、服装风格)
- personality: 性格特征 (详细，如高冷、热血、腹黑)
- background: 背景故事 (结合世界观的个人经历)
- identity_job: 职业或身份
- relation: 与主角的关系类型
- relation_desc: 关系详情描述 (具体的互动模式)

请严格返回 JSON 格式，不要包含 Markdown 代码块标记。`;

                // 2. 调用 AI
                const resultStr = await callAI([
                    { role: "system", content: "你是一个只输出 JSON 数组的辅助系统。" },
                    { role: "user", content: prompt }
                ]);

                // 3. 解析 JSON
                const npcs = extractAndParseJSON(resultStr);
                if (!Array.isArray(npcs)) throw new Error("AI 返回格式错误 (不是数组) 或解析失败");

                // 4. 批量写入 DB 并建立关系
                let newCount = 0;
                for (const npcData of npcs) {
                    // 整合详细描述
                    const fullDesc = `【外貌】\n${npcData.appearance || '无'}\n\n【性格】\n${npcData.personality || '无'}\n\n【背景】\n${npcData.background || npcData.description || '无'}`;
                    
                    // 构造 NPC 数据
                    const newNpc = {
                        name: npcData.name,
                        nick: npcData.nickname || '',
                        description: fullDesc, // 存入整合后的详细描述
                        type: 'npc', // 默认为 NPC 类型
                        avatar: '', // 暂时留空
                        lorebookIds: sourceLorebookIds.length > 0 ? sourceLorebookIds : null, // 继承多个世界书
                        lorebookId: sourceLorebookIds.length > 0 ? sourceLorebookIds[0] : null, // 兼容字段
                        identity: {
                            // 基础身份占位
                            job: npcData.identity_job
                        },
                        relationships: [
                            // 写入指向主角的关系
                            {
                                targetId: sourceChar.id,
                                targetName: sourceChar.name,
                                relation: "关联主角", // 相对关系，或者让AI生成反向关系比较复杂，这里简化
                                desc: "生成来源"
                            }
                        ],
                        updated_at: Date.now()
                    };
                    
                    const newId = await db.characters.add(newNpc);
                    newCount++;
                    
                    // NPC生成后默认为陌生人，需要用户自己添加好友
                    console.log(`[NPC生成] ✅ ${newNpc.name} 已创建（默认陌生人，需手动添加好友）`);

                    // 5. 更新主角的关系列表
                    if (!sourceChar.relationships) sourceChar.relationships = [];
                    sourceChar.relationships.push({
                        targetId: newId,
                        targetName: newNpc.name,
                        relation: npcData.relation,
                        desc: npcData.relation_desc
                    });
                }
                
                // 保存主角更新
                await safeCharacterPut(sourceChar);

                // 6. 刷新界面
                alert(`✅ 成功生成 ${newCount} 个 NPC！\n\n💡 提示：你可以在「角色档案 > NPC」标签页中查看和编辑这些生成的NPC。`);
                closeModal('npc-gen-modal');
                // 刷新编辑页的关系列表
                renderRelationList(sourceChar);
                // 刷新外部列表 (如果在列表页的话，虽然现在在弹窗里)
                loadCharacterList();

            } catch (err) {
                console.error(err);
                alert("生成失败: " + err.message);
            } finally {
                btn.innerText = "开始生成";
                btn.disabled = false;
            }
        }

        function hideCharacterEditor() {
            document.getElementById('character-editor-page').style.display = 'none';
            editingCharId = null;
        }

        function handleCharAvatarInput(input) {
            const file = input.files[0];
            if (file) {
                const reader = new FileReader();
                reader.onload = e => {
                    document.getElementById('char-avatar-preview').style.backgroundImage = `url(${e.target.result})`;
                    document.getElementById('char-avatar-placeholder').style.display = 'none';
                };
                reader.readAsDataURL(file);
            }
        }

        async function saveCharacter() {
            const name = document.getElementById('char-name').value.trim();
            const nick = document.getElementById('char-nick').value.trim();
            const desc = document.getElementById('char-desc').value;
            const type = document.getElementById('char-type').value;
            
            // 如果是更新，先获取旧数据以保留 lorebookId, wechat_registered 等字段
            let oldData = {};
            if (editingCharId) {
                oldData = await db.characters.get(editingCharId) || {};
            }
            
            // 获取虚拟身份数据（合并旧数据，保留 wechat_registered, registered_at 等注册状态）
            const identity = {
                ...(oldData.identity || {}), // 保留已有的 wechat_registered, registered_at 等字段
                account: document.getElementById('char-identity-account').value.trim(),
                password: document.getElementById('char-identity-password').value.trim(),
                phone: document.getElementById('char-identity-phone').value.trim(),
                address: document.getElementById('char-identity-address').value.trim(),
                id_card: document.getElementById('char-identity-id').value.trim(),
                bank_card: document.getElementById('char-identity-bank').value.trim(),
                bank_password: document.getElementById('char-identity-bank-pass').value.trim()
            };

            // 获取头像 Base64
            let avatar = '';
            const bgImage = document.getElementById('char-avatar-preview').style.backgroundImage;
            if (bgImage && bgImage !== 'none') {
                avatar = bgImage.replace(/url\(|\)|"/g, '');
            }
            
            if (!name) {
                alert("请输入角色名字");
                return;
            }

            const charData = {
                ...oldData, // 保留原有的 lorebookId, original_data 等
                name,
                nick,
                description: desc,
                type,
                avatar,
                identity, // 保存身份信息
                updated_at: Date.now()
            };
            
            if (editingCharId) {
                await safeCharacterPut(charData); // 使用 put 覆盖完整对象
            } else {
                await db.characters.add(charData);
            }
            
            hideCharacterEditor();
            // 如果修改了类型，可能需要跳转到对应 Tab 才能看到，或者直接刷新当前 Tab
            if (type !== currentCharacterType) {
                switchCharacterTab(type);
            } else {
                loadCharacterList();
            }
            
            // ✅ 如果当前有打开的聊天窗口且是这个角色，刷新聊天界面（头像/昵称等可能变了）
            if (editingCharId && currentChatCharId === editingCharId) {
                const updatedChar = await db.characters.get(editingCharId);
                if (updatedChar) {
                    // 更新聊天标题
                    const _editAid = getCurrentAccountId();
                    const titleEl = document.getElementById('chat-title');
                    if (titleEl) titleEl.innerText = getCharDisplayName(updatedChar, _editAid);
                    // 强制刷新聊天消息（头像会随之更新）
                    renderChatBody(updatedChar, true);
                }
            }
            
            // ✅ 刷新微信聊天列表（头像/昵称可能变了）
            const wechatContent = document.getElementById('wechat-content');
            if (wechatContent) {
                renderWechatList(wechatContent);
            }
        }

        // 提取并解析 JSON 的通用辅助函数 (增强鲁棒性)
        function extractAndParseJSON(text) {
            if (!text) return null;
            let str = text.trim();
            
            // 1. 尝试提取最外层的 { ... } 或 [ ... ]
            // 这能有效忽略前后的杂质（如用户的 ]{...} 情况）
            const firstBrace = str.indexOf('{');
            const firstBracket = str.indexOf('[');
            
            let startIdx = -1;
            let isArray = false;
            
            // 确定是对象还是数组开始得更早
            if (firstBrace !== -1 && (firstBracket === -1 || firstBrace < firstBracket)) {
                startIdx = firstBrace;
            } else if (firstBracket !== -1) {
                startIdx = firstBracket;
                isArray = true;
            }
            
            if (startIdx !== -1) {
                const endChar = isArray ? ']' : '}';
                const endIdx = str.lastIndexOf(endChar);
                
                if (endIdx !== -1 && endIdx > startIdx) {
                    const jsonCandidate = str.substring(startIdx, endIdx + 1);
                    try {
                        return JSON.parse(jsonCandidate);
                    } catch (e) {
                        // 尝试修复常见 JSON 错误（尾部多余逗号）
                        try {
                            const fixed = jsonCandidate.replace(/,\s*([}\]])/g, '$1');
                            return JSON.parse(fixed);
                        } catch (e2) {
                            // console.warn("[extractJSON] 提取片段解析失败:", e2);
                        }
                    }
                }
            }
            
            // 2. 如果提取失败，尝试清理 Markdown 标记后直接解析
            const cleanStr = str.replace(/^```json\s*/i, '').replace(/^```\s*/, '').replace(/\s*```$/, '');
            try {
                return JSON.parse(cleanStr);
            } catch (e) {
                // 再尝试修复尾部多余逗号
                try {
                    const fixed = cleanStr.replace(/,\s*([}\]])/g, '$1');
                    return JSON.parse(fixed);
                } catch (e2) {
                    return null;
                }
            }
        }

        // 从可能损坏的 JSON 文本中，尽量提取字符串字段值（如 reply/thought）
        function extractJsonStringValue(text, fieldName) {
            if (!text || !fieldName) return '';
            const key = `"${fieldName}"`;
            const keyIdx = text.indexOf(key);
            if (keyIdx === -1) return '';
            const colonIdx = text.indexOf(':', keyIdx + key.length);
            if (colonIdx === -1) return '';
            
            // 找到冒号后的第一个引号
            let i = colonIdx + 1;
            while (i < text.length && /\s/.test(text[i])) i++;
            if (text[i] !== '"') return '';
            i++; // 跳过起始引号
            
            let buf = '';
            let escaped = false;
            for (; i < text.length; i++) {
                const ch = text[i];
                if (escaped) {
                    buf += ch;
                    escaped = false;
                    continue;
                }
                if (ch === '\\') {
                    buf += ch;
                    escaped = true;
                    continue;
                }
                if (ch === '"') break; // 字符串结束
                buf += ch;
            }
            
            if (!buf) return '';
            try {
                // 通过 JSON.parse 做一次转义还原
                return JSON.parse(`"${buf}"`);
            } catch (e) {
                return buf
                    .replace(/\\n/g, '\n')
                    .replace(/\\"/g, '"')
                    .replace(/\\t/g, '\t')
                    .replace(/\\\\/g, '\\');
            }
        }

        // ========== 外语+中文翻译识别功能 ==========
        // 解析AI返回的外语+中文组合消息
        // 支持格式：
        // 1. "外语（中文翻译）" 或 "外语(中文翻译)"
        // 2. "外语「中文翻译」"
        // 3. 外语中包含括号的情况（取最后一个含中文的括号作为翻译）
        function parseForeignWithTranslation(text) {
            if (!text) return null;
            
            // ✅ 策略：从末尾找最后一个包含中文的括号对，作为翻译
            // 这样即使外语文本中有括号也不会误判
            
            // 模式1: 从末尾匹配最后一个（中文翻译）或 (中文翻译)
            // 使用贪婪匹配 .* 来尽可能多地匹配外语部分（取最后一个括号）
            const pattern1 = /^([\s\S]+)[（(]([\s\S]*[\u4e00-\u9fff][\s\S]*)[）)]$/;
            let match = text.match(pattern1);
            if (match) {
                const foreign = match[1].trim();
                const chinese = match[2].trim();
                // 验证：括号内包含中文，外语部分不为空，且外语部分不全是中文
                if (foreign && chinese && containsChinese(chinese) && !isAllChinese(foreign)) {
                    return { foreign, chinese };
                }
            }
            
            // 模式2: 任意内容「中文翻译」
            const pattern2 = /^([\s\S]+)「([\s\S]*[\u4e00-\u9fff][\s\S]*)」$/;
            match = text.match(pattern2);
            if (match) {
                const foreign = match[1].trim();
                const chinese = match[2].trim();
                if (foreign && chinese && containsChinese(chinese) && !isAllChinese(foreign)) {
                    return { foreign, chinese };
                }
            }
            
            // 模式3: 末尾有翻译但前面可能有换行 - 比如 "外语\n（中文翻译）"
            const pattern3 = /^([\s\S]+?)\s*[（(]([\s\S]*[\u4e00-\u9fff][\s\S]*)[）)]\s*$/;
            match = text.match(pattern3);
            if (match) {
                const foreign = match[1].trim();
                const chinese = match[2].trim();
                if (foreign && chinese && containsChinese(chinese) && !isAllChinese(foreign)) {
                    return { foreign, chinese };
                }
            }
            
            return null;
        }
        
        // 检查文本是否几乎全是中文（用于排除纯中文消息被误判为翻译）
        function isAllChinese(text) {
            if (!text) return false;
            const cleaned = text.replace(/[\s\p{P}\p{S}\d]/gu, ''); // 去除空格、标点、符号、数字
            if (cleaned.length === 0) return false;
            const chineseChars = cleaned.match(/[\u4e00-\u9fff]/g) || [];
            return chineseChars.length / cleaned.length > 0.8; // 超过80%是中文就认为是纯中文
        }
        
        // 检查文本是否包含中文
        function containsChinese(text) {
            if (!text) return false;
            const chineseRegex = /[\u4e00-\u9fff]/;
            return chineseRegex.test(text);
        }
        
        // ✅ 核心：构建角色消息对象，一次性解析翻译（只在此处调用 parseForeignWithTranslation）
        // 所有 role:'char' 的消息都应通过此函数创建，确保翻译只解析一次
        function buildCharMessage(content, isForeignLangMode, extraFields = {}) {
            const msg = { 
                role: 'char', 
                content: content, 
                time: Date.now(),
                ...extraFields
            };
            
            // 外语翻译模式：在存储时就解析好翻译，避免渲染时重复解析
            if (isForeignLangMode && content && typeof content === 'string') {
                // 跳过特殊格式消息（图片、语音、表情包等）
                if (!content.startsWith('[img:') && !content.startsWith('[voice:') && 
                    !content.startsWith('[imgcard:') && !content.startsWith('[sticker:') &&
                    !content.startsWith('[emei_') && !content.startsWith('[couple_avatar_card]') &&
                    !content.startsWith('[payment_request]')) {
                    const parsed = parseForeignWithTranslation(content);
                    if (parsed) {
                        msg.foreignText = parsed.foreign;
                        msg.chineseText = parsed.chinese;
                    }
                }
            }
            
            return msg;
        }
        
        // 通用 AI 调用函数
        async function callAI(messages, options = {}) {
            // 兼容 callAI(msgs, 0.88) 旧写法：第二参为数字时视为 temperature
            if (typeof options === 'number' && !isNaN(options)) {
                options = { temperature: options };
            } else if (options == null || typeof options !== 'object' || Array.isArray(options)) {
                options = {};
            }

            let urlValue = '';
            let apiKeyValue = '';
            let modelValue = '';
            let temperature = 0.7;
            
            // 🔌 副API支持：如果指定了 _useSecondary 且副API已配置，优先使用副API
            const useSecondary = options._useSecondary;
            let isUsingSecondary = false;
            if (useSecondary) {
                // 尝试从副API缓存获取配置
                const secUrl = _secondaryApiConfigCache.url;
                const secKey = _secondaryApiConfigCache.key;
                const secModel = _secondaryApiConfigCache.model;
                if (secUrl && secKey && secModel) {
                    // 副API完整配置，直接使用
                    urlValue = secUrl;
                    apiKeyValue = secKey;
                    modelValue = secModel;
                    isUsingSecondary = true;
                    console.log('[callAI] 🔌 使用副API配置');
                } else if (secUrl || secKey || secModel) {
                    // 副API部分配置，已配置的字段使用副API，缺失的字段从主API补全
                    if (secUrl) urlValue = secUrl;
                    if (secKey) apiKeyValue = secKey;
                    if (secModel) modelValue = secModel;
                    console.log('[callAI] 🔌 副API部分配置，缺失项将从主API补全');
                    // isUsingSecondary 保持 false，让后面的逻辑补全缺失的字段
                } else {
                    // 副API完全未配置，静默回退到主API
                    console.log('[callAI] ℹ️ 副API未配置，回退到主API');
                }
            }
            
            // 如果不是使用副API（或副API未配置），使用主API配置
            if (!isUsingSecondary) {
            // 🔧 修复手机端第二次API调用卡死：优先使用内存缓存，避免IndexedDB事务阻塞
            if (_apiConfigCache.url && _apiConfigCache.key && _apiConfigCache.model) {
                // 内存缓存有效，直接使用（跳过可能挂起的DB读取）
                urlValue = urlValue || _apiConfigCache.url;
                apiKeyValue = apiKeyValue || _apiConfigCache.key;
                modelValue = modelValue || _apiConfigCache.model;
                temperature = _apiConfigCache.temp ? parseFloat(_apiConfigCache.temp) : 0.7;
                console.log('[callAI] ✅ 使用内存缓存的API配置');
                
                // 后台静默刷新缓存（不阻塞当前调用，加超时保护）
                Promise.race([
                    (async () => {
                        try {
                            const url = await db.dexiData.get('aiBaseUrl');
                            const key = await db.dexiData.get('aiApiKey');
                            const model = await db.dexiData.get('aiCurrentModel');
                            const tempItem = await db.dexiData.get('aiTemperature');
                            const u = url?.value?.trim() || '';
                            const k = key?.value?.trim() || '';
                            const m = model?.value?.trim() || '';
                            if (u && k && m) {
                                _apiConfigCache = { url: u, key: k, model: m, temp: String(tempItem ? parseFloat(tempItem.value) : 0.7) };
                            }
                        } catch (e) {
                            console.warn('[callAI] 后台刷新缓存失败:', e.message);
                        }
                    })(),
                    new Promise(r => setTimeout(r, 3000)) // 3秒超时
                ]).catch(() => {});
            } else {
                // 内存缓存为空（首次调用），从DB读取，加超时保护
                try {
                    const dbReadResult = await Promise.race([
                        (async () => {
                            const url = await db.dexiData.get('aiBaseUrl');
                            const key = await db.dexiData.get('aiApiKey');
                            const model = await db.dexiData.get('aiCurrentModel');
                            const tempItem = await db.dexiData.get('aiTemperature');
                            return { url, key, model, tempItem };
                        })(),
                        new Promise((_, reject) => setTimeout(() => reject(new Error('DB读取超时')), 5000))
                    ]);
                    
                    urlValue = urlValue || dbReadResult.url?.value?.trim() || '';
                    apiKeyValue = apiKeyValue || dbReadResult.key?.value?.trim() || '';
                    modelValue = modelValue || dbReadResult.model?.value?.trim() || '';
                    temperature = dbReadResult.tempItem ? parseFloat(dbReadResult.tempItem.value) : 0.7;
                    
                    // 成功读取后更新内存缓存
                    if (urlValue && apiKeyValue && modelValue) {
                        _apiConfigCache = { url: urlValue, key: apiKeyValue, model: modelValue, temp: String(temperature) };
                        console.log('[callAI] ✅ 从DB读取API配置并缓存');
                    }
                } catch (dbErr) {
                    console.warn('[callAI] 数据库读取失败或超时，尝试使用内存缓存:', dbErr.message);
                }
                
                // 如果DB读取失败/超时，尝试使用内存缓存
                if (!urlValue && _apiConfigCache.url) {
                    urlValue = _apiConfigCache.url;
                }
                if (!apiKeyValue && _apiConfigCache.key) {
                    apiKeyValue = _apiConfigCache.key;
                }
                if (!modelValue && _apiConfigCache.model) {
                    modelValue = _apiConfigCache.model;
                }
            }
            
            // 🔧 最终兜底：如果内存缓存和DB都失败，尝试从localStorage读取备份
            if (!apiKeyValue) {
                const lsKey = localStorage.getItem('aiApiKey');
                if (lsKey && lsKey.trim()) {
                    apiKeyValue = lsKey.trim();
                    console.warn('[callAI] ⚠️ 使用localStorage备份的API密钥');
                    // 恢复到内存缓存
                    _apiConfigCache.key = apiKeyValue;
                }
            }
            if (!urlValue) {
                const lsUrl = localStorage.getItem('aiBaseUrl');
                if (lsUrl && lsUrl.trim()) {
                    urlValue = lsUrl.trim();
                    console.warn('[callAI] ⚠️ 使用localStorage备份的API地址');
                    _apiConfigCache.url = urlValue;
                }
            }
            if (!modelValue) {
                const lsModel = localStorage.getItem('aiCurrentModel');
                if (lsModel && lsModel.trim()) {
                    modelValue = lsModel.trim();
                    console.warn('[callAI] ⚠️ 使用localStorage备份的模型');
                    _apiConfigCache.model = modelValue;
                }
            }
            } // end if (!isUsingSecondary)
            
            if (!urlValue) {
                throw new Error("请先在设置中配置 API 地址");
            }
            if (!apiKeyValue) {
                throw new Error("API 密钥不能为空，请在设置中配置");
            }
            if (!modelValue) {
                throw new Error("模型名称不能为空，请在设置中选择模型");
            }
            
            // 检查 API Key 格式（基本检查）
            if (apiKeyValue.length < 10) {
                console.warn('[callAI] API Key 长度异常，可能无效:', apiKeyValue.length);
            }
            
            // 验证温度值
            if (isNaN(temperature) || temperature < 0 || temperature > 2) {
                console.warn('[callAI] 温度值无效:', temperature, '，使用默认值 0.7');
                temperature = 0.7;
            }
            if (typeof options.temperature === 'number' && !isNaN(options.temperature)) {
                temperature = options.temperature;
                if (temperature < 0 || temperature > 2) {
                    console.warn('[callAI] 调用方 temperature 越界，已夹紧到 0~2');
                    temperature = Math.min(2, Math.max(0, temperature));
                }
            }
            
            // 获取 max_tokens 配置（如果提供）
            const maxTokens = options.max_tokens || options.maxTokens;

            const requestUrl = getSmartUrl(urlValue, '/chat/completions');
            
            // ✅ 全局防御：清洗 messages，防止空内容或非法格式导致 400 错误
            // 支持多模态消息格式（图片识别）：content 可以是字符串或数组
            const cleanMessages = messages.map(m => {
                // 验证 role 字段
                let role = m.role;
                if (!role || !['system', 'user', 'assistant'].includes(role)) {
                    console.warn('[callAI] 无效的 role:', role, '，使用 user');
                    role = 'user';
                }
                
                let content = m.content;
                
                // 支持多模态内容（数组格式，用于图片识别）
                if (Array.isArray(content)) {
                    // ⚠️ 防御：OpenAI API 只允许 user 角色包含 image_url，assistant 角色带 image_url 会导致 400
                    // 如果是 assistant 消息且包含 image_url，降级为纯文字
                    if (role === 'assistant') {
                        const textParts = content.filter(part => part.type === 'text' && part.text && part.text.trim().length > 0);
                        const textContent = textParts.map(p => p.text).join(' ').trim();
                        return { role, content: textContent || '（发送了一张图片）' };
                    }
                    
                    // 验证数组中每个元素
                    const validParts = content.filter(part => {
                        if (part.type === 'text') return part.text && part.text.trim().length > 0;
                        if (part.type === 'image_url') return part.image_url && part.image_url.url;
                        return false;
                    });
                    if (validParts.length === 0) return { role, content: '' };
                    // 🔧 标记包含图片的消息，后续异步转换格式
                    return { role, content: validParts, _hasImage: true };
                }
                
                // 确保 content 是字符串
                if (content === null || content === undefined) content = "";
                if (typeof content !== 'string') content = String(content);
                
                return {
                    role: role,
                    content: content.trim()
                };
            }).filter(m => {
                if (Array.isArray(m.content)) return m.content.length > 0;
                return m.content.length > 0;
            }); // 再次过滤空消息

            // 🔧 异步转换图片格式：将 avif/webp 等不兼容格式转为 JPEG，HTTP URL 转为 base64
            for (let i = 0; i < cleanMessages.length; i++) {
                const msg = cleanMessages[i];
                if (msg._hasImage && Array.isArray(msg.content)) {
                    for (let j = msg.content.length - 1; j >= 0; j--) {
                        const part = msg.content[j];
                        if (part.type === 'image_url' && part.image_url && part.image_url.url) {
                            const url = part.image_url.url;
                            // 处理 HTTP URL：先转为 base64
                            if (url.startsWith('http')) {
                                try {
                                    const base64Url = await convertHttpImageToBase64(url);
                                    if (base64Url.startsWith('data:image')) {
                                        part.image_url.url = await convertImageForAI(base64Url);
                                    } else {
                                        // CORS 失败，移除图片部分，保留文字描述
                                        console.warn('[callAI] HTTP图片无法转为base64（CORS），移除图片部分');
                                        msg.content.splice(j, 1);
                                    }
                                } catch (e) {
                                    console.warn('[callAI] HTTP图片转换失败，移除图片部分:', e);
                                    msg.content.splice(j, 1);
                                }
                            }
                            // 处理 data: URL：格式转换
                            else if (url.startsWith('data:image')) {
                                try {
                                    const converted = await convertImageForAI(url);
                                    part.image_url.url = converted;
                                } catch (e) {
                                    console.warn('[callAI] 图片格式转换失败，使用原始格式:', e);
                                }
                            }
                        }
                    }
                    delete msg._hasImage; // 清理标记
                    // 如果图片都被移除了，且只剩文字，转回字符串格式
                    const hasImage = msg.content.some(p => p.type === 'image_url');
                    if (!hasImage && msg.content.length === 1 && msg.content[0].type === 'text') {
                        msg.content = msg.content[0].text;
                    }
                }
            }

            // 如果过滤后只剩下 system 消息，有些模型可能会报错，但大多数支持。
            // 这里我们不做 System 的强制检查，只要不为空即可。
            if (cleanMessages.length === 0) {
                throw new Error("请求中止：没有有效的消息内容（可能是因为消息被撤回或为空）");
            }
            
            // 验证是否至少有一条非 system 消息
            const hasNonSystemMessage = cleanMessages.some(m => m.role !== 'system');
            if (!hasNonSystemMessage) {
                console.warn('[callAI] 只有 system 消息，添加一个占位 user 消息');
                // 🔧 修复：添加更完整的占位消息，避免 Gemini 代理返回空 choices
                cleanMessages.push({
                    role: 'user',
                    content: '请根据你的人设，发送一条消息。保持角色扮演，自然地开始或继续对话。'
                });
            }

            let rawText = '';
            
            // 构建请求体
            const requestBody = {
                apiUrl: requestUrl,
                apiKey: apiKeyValue,
                model: modelValue,
                messages: cleanMessages,
                temperature: temperature
            };
            
            // 添加详细的调试日志
            console.log('[callAI] 🚀 准备发送请求');
            console.log('[callAI] API URL:', requestUrl);
            console.log('[callAI] Model:', modelValue);
            console.log('[callAI] API Key length:', apiKeyValue.length);
            console.log('[callAI] Temperature:', temperature);
            console.log('[callAI] Messages count:', cleanMessages.length);
            console.log('[callAI] Messages preview:', cleanMessages.map(m => ({
                role: m.role,
                content: Array.isArray(m.content) 
                    ? `[多模态: ${m.content.map(p => p.type === 'image_url' ? '🖼️图片' : p.text?.substring(0, 50)).join(' + ')}]`
                    : m.content.substring(0, 100) + (m.content.length > 100 ? '...' : '')
            })));
            
            // 纯前端：直接调用 AI API（需要配置支持 CORS 的 API 端点）
            try {
                // 🔥 构建请求体，支持 response_format 强制 JSON 输出
                const fetchBody = {
                    model: modelValue,
                    messages: cleanMessages,
                    temperature: temperature
                };
                
                // 如果调用方要求 JSON 输出，添加 response_format 参数
                if (options.json_mode) {
                    fetchBody.response_format = { type: "json_object" };
                    console.log('[callAI] 📋 已启用 JSON 模式 (response_format: json_object)');
                }
                
                // 如果有 max_tokens 参数
                if (maxTokens) {
                    fetchBody.max_tokens = maxTokens;
                }
                
                const bodyStr = JSON.stringify(fetchBody);
                console.log('[callAI] 📦 请求体大小:', (bodyStr.length / 1024).toFixed(1), 'KB');
                
                // 🔧 封装fetch调用，支持401重试
                let currentApiKey = apiKeyValue;
                let res = await fetch(requestUrl, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'Authorization': `Bearer ${currentApiKey}`
                    },
                    body: bodyStr
                });

                // 🔧 修复401循环报错：如果收到401/403，从DB重新读取密钥并重试一次
                if ((res.status === 401 || res.status === 403) && !options._isRetry) {
                    console.warn('[callAI] ⚠️ 收到', res.status, '错误，尝试从数据库重新读取API密钥并重试...');
                    try {
                        const freshKey = await db.dexiData.get('aiApiKey');
                        const freshKeyValue = freshKey?.value?.trim() || '';
                        if (freshKeyValue && freshKeyValue !== currentApiKey) {
                            console.log('[callAI] 🔄 检测到DB中密钥与缓存不同，使用DB密钥重试');
                            console.log('[callAI]   缓存密钥长度:', currentApiKey.length, '| DB密钥长度:', freshKeyValue.length);
                            currentApiKey = freshKeyValue;
                            // 同步修正内存缓存
                            _apiConfigCache.key = freshKeyValue;
                        } else if (freshKeyValue) {
                            console.log('[callAI] 🔄 DB密钥与缓存一致，仍然重试一次（可能是代理临时故障）');
                        }
                        if (freshKeyValue) {
                            res = await fetch(requestUrl, {
                                method: 'POST',
                                headers: {
                                    'Content-Type': 'application/json',
                                    'Authorization': `Bearer ${freshKeyValue}`
                                },
                                body: bodyStr
                            });
                            if (res.ok) {
                                console.log('[callAI] ✅ 重试成功！');
                            } else {
                                console.error('[callAI] ❌ 重试仍失败，状态码:', res.status);
                            }
                        }
                    } catch (retryErr) {
                        console.error('[callAI] 重试过程出错:', retryErr.message);
                    }
                }

                if (!res.ok) {
                    const errText = await res.text();
                    console.error('[callAI] ❌ API 请求失败');
                    console.error('[callAI] 状态码:', res.status);
                    console.error('[callAI] 错误响应:', errText);
                    console.error('[callAI] 使用的密钥长度:', currentApiKey.length, '前4字符:', currentApiKey.substring(0, 4) + '...');
                    
                    try {
                        const errJson = JSON.parse(errText);
                        console.error('[callAI] 解析后的错误:', errJson);
                        if (errJson.error) {
                            const errorMsg = `AI请求失败 (${res.status}): ${errJson.error}${errJson.details ? '\n详情: ' + errJson.details : ''}`;
                            throw new Error(errorMsg);
                        }
                    } catch(parseErr) {
                        // 如果不是 JSON 格式的错误
                        if (parseErr instanceof SyntaxError) {
                            console.error('[callAI] 错误响应不是 JSON 格式');
                        }
                    }
                    
                    throw new Error(`API 请求失败: ${res.status} - ${errText.substring(0, 200)}`);
                }

                // ✅ 关键改动：先获取原始文本，而不是直接 .json()
                rawText = await res.text();
                
                // 尝试解析为 JSON
                let data;
                try {
                    data = JSON.parse(rawText);
                } catch (parseErr) {
                    // 返回的不是 JSON（可能是 HTML 错误页、纯文本等）
                    console.warn('[callAI] 返回内容不是有效的 JSON，直接使用原始文本');
                    console.log('[callAI] 原始返回:', rawText.substring(0, 500));
                    
                    // 直接返回原始文本（去除 HTML 标签和特殊字符）
                    return rawText
                        .replace(/<[^>]*>/g, '') // 移除 HTML 标签
                        .replace(/[◇◆★☆●○■□▲△]/g, '') // 移除装饰字符
                        .replace(/\s*\[DONE\]\s*$/i, '') // 移除末尾 [DONE]
                        .trim();
                }
                
                // 🚨 检测空的 choices 数组（API调用成功但没有返回内容）
                if (data?.choices && Array.isArray(data.choices) && data.choices.length === 0) {
                    console.error('[callAI] ❌ API返回了空的choices数组');
                    console.error('[callAI] 完整响应:', JSON.stringify(data, null, 2));
                    
                    let errorMsg = 'API调用成功，但没有返回内容';
                    
                    // 检查usage信息，判断可能的原因
                    if (data.usage) {
                        const { prompt_tokens, completion_tokens, total_tokens } = data.usage;
                        if (prompt_tokens === 0 && completion_tokens === 0) {
                            errorMsg += '\n\n💡 可能的原因：\n';
                            errorMsg += '- 内容被安全过滤拦截\n';
                            errorMsg += '- 模型不支持当前请求\n';
                            errorMsg += '- API配额不足或限流\n';
                            errorMsg += '- 请求参数格式错误';
                        }
                    }
                    
                    throw new Error(errorMsg);
                }
                
                // ✅ 兼容多种返回路径（包括Gemini）
                let content = '';
                
                // 1. Gemini格式：data.candidates[0].content.parts[0].text
                if (data?.candidates?.[0]?.content?.parts?.[0]?.text) {
                    content = data.candidates[0].content.parts[0].text;
                    console.log('[callAI] ✅ 使用Gemini格式提取内容');
                }
                // 2. OpenAI标准格式：data.choices[0].message.content
                else if (data?.choices?.[0]?.message?.content) {
                    content = data.choices[0].message.content;
                    console.log('[callAI] ✅ 使用OpenAI格式提取内容');
                }
                // 3. 其他兼容格式
                else {
                    content = 
                        data?.choices?.[0]?.text ??              // 一些旧版 API
                        data?.output_text ??                     // 一些自定义格式
                        data?.message ??                         // 简化格式
                        data?.content ??                         // 直接返回内容
                        data?.reply ??                           // 自定义字段
                        '';
                }
                
                // ✅ 清理末尾的 [DONE] / [done]（某些API代理会把SSE终止信号混入内容）
                if (content) {
                    content = content.replace(/\s*\[DONE\]\s*$/i, '').replace(/\s*\[done\]\s*$/i, '').trim();
                }
                
                if (!content) {
                    // 如果所有路径都没有内容，记录详细日志
                    console.error('[callAI] ❌ 无法从任何路径提取内容');
                    console.error('[callAI] 完整响应结构:', JSON.stringify(data, null, 2).substring(0, 1000));
                    
                    // 检查是否是Gemini的空返回
                    if (data?.candidates && Array.isArray(data.candidates) && data.candidates.length === 0) {
                        throw new Error('Gemini API返回了空的candidates数组，可能是内容被过滤或请求格式错误');
                    }
                    
                    // 如果data本身就是字符串，检查是否是JSON字符串
                    if (typeof data === 'string') {
                        // 如果是JSON字符串，尝试解析
                        try {
                            const parsed = JSON.parse(data);
                            // 如果解析成功，递归调用提取逻辑
                            if (parsed.candidates?.[0]?.content?.parts?.[0]?.text) {
                                return parsed.candidates[0].content.parts[0].text;
                            }
                            if (parsed.choices?.[0]?.message?.content) {
                                return parsed.choices[0].message.content;
                            }
                        } catch {
                            // 不是JSON，直接返回字符串
                            return data;
                        }
                    }
                    
                    // 🚨 最后检查：如果rawText看起来像JSON对象，不要返回它
                    if (rawText.trim().startsWith('{') && rawText.trim().endsWith('}')) {
                        console.error('[callAI] ❌ 检测到返回的是原始JSON对象，不应该显示给用户');
                        throw new Error('API返回了原始JSON对象而非文本内容。这可能是API配置问题或模型响应格式错误。');
                    }
                    
                    // 最后尝试：返回清理后的原始文本（但这种情况不应该发生）
                    const fallback = rawText
                        .replace(/<[^>]*>/g, '')
                        .replace(/[◇◆★☆●○■□▲△]/g, '')
                        .trim();
                    
                    if (fallback && fallback.length > 10 && !fallback.startsWith('{')) {
                        console.warn('[callAI] ⚠️ 使用原始文本作为fallback');
                        return fallback;
                    }
                    
                    throw new Error('API返回了空内容，无法提取有效文本。请检查API配置和模型响应。');
                }
                
                return content;
                
            } catch (err) {
                console.error("[callAI] 错误详情:", err);
                console.log("[callAI] 原始返回内容:", rawText.substring(0, 500));
                throw err;
            }
        }

        // ✅ 流式AI调用函数（三阶段处理模型）
        async function callAIStream(messages, options = {}) {
            let urlValue = '';
            let apiKeyValue = '';
            let modelValue = '';
            let temperature = 0.7;
            
            try {
                const url = await db.dexiData.get('aiBaseUrl');
                const key = await db.dexiData.get('aiApiKey');
                const model = await db.dexiData.get('aiCurrentModel');
                
                urlValue = url?.value?.trim() || '';
                apiKeyValue = key?.value?.trim() || '';
                modelValue = model?.value?.trim() || '';
                
                const tempItem = await db.dexiData.get('aiTemperature');
                temperature = tempItem ? parseFloat(tempItem.value) : 0.7;
            } catch (dbErr) {
                console.warn('[callAIStream] 数据库读取失败:', dbErr.message);
            }
            
            if (!urlValue || !apiKeyValue || !modelValue) {
                throw new Error("请先在设置中配置 API 地址、密钥和模型");
            }
            
            const requestUrl = getSmartUrl(urlValue, '/chat/completions');
            
            // 清洗 messages（复用 callAI 的逻辑）
            const cleanMessages = messages.map(m => {
                let role = m.role;
                if (!role || !['system', 'user', 'assistant'].includes(role)) {
                    role = 'user';
                }
                
                let content = m.content;
                if (Array.isArray(content)) {
                    // ⚠️ 防御：OpenAI API 只允许 user 角色包含 image_url，assistant 角色带 image_url 会导致 400
                    if (role === 'assistant') {
                        const textParts = content.filter(part => part.type === 'text' && part.text && part.text.trim().length > 0);
                        const textContent = textParts.map(p => p.text).join(' ').trim();
                        return { role, content: textContent || '（发送了一张图片）' };
                    }
                    
                    const validParts = content.filter(part => {
                        if (part.type === 'text') return part.text && part.text.trim().length > 0;
                        if (part.type === 'image_url') return part.image_url && part.image_url.url;
                        return false;
                    });
                    if (validParts.length === 0) return { role, content: '' };
                    return { role, content: validParts };
                }
                
                if (content === null || content === undefined) content = "";
                if (typeof content !== 'string') content = String(content);
                
                return {
                    role: role,
                    content: content.trim()
                };
            }).filter(m => {
                if (Array.isArray(m.content)) return m.content.length > 0;
                return m.content.length > 0;
            });
            
            if (cleanMessages.length === 0) {
                throw new Error("请求中止：没有有效的消息内容");
            }
            
            // 🎯 第一阶段：流式层 - 只做字符串拼接
            let rawText = '';
            let buffer = '';
            const decoder = new TextDecoder();
            
            try {
                const streamBody = JSON.stringify({
                    model: modelValue,
                    messages: cleanMessages,
                    temperature: temperature,
                    stream: true  // 启用流式响应
                });
                
                let currentApiKey = apiKeyValue;
                let res = await fetch(requestUrl, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'Authorization': `Bearer ${currentApiKey}`
                    },
                    body: streamBody
                });
                
                // 🔧 修复401循环报错：如果收到401/403，从DB重新读取密钥并重试一次
                if (res.status === 401 || res.status === 403) {
                    console.warn('[callAIStream] ⚠️ 收到', res.status, '错误，尝试从数据库重新读取API密钥并重试...');
                    try {
                        const freshKey = await db.dexiData.get('aiApiKey');
                        const freshKeyValue = freshKey?.value?.trim() || '';
                        if (freshKeyValue && freshKeyValue !== currentApiKey) {
                            console.log('[callAIStream] 🔄 检测到DB中密钥与缓存不同，使用DB密钥重试');
                            currentApiKey = freshKeyValue;
                            _apiConfigCache.key = freshKeyValue;
                        }
                        if (freshKeyValue) {
                            res = await fetch(requestUrl, {
                                method: 'POST',
                                headers: {
                                    'Content-Type': 'application/json',
                                    'Authorization': `Bearer ${freshKeyValue}`
                                },
                                body: streamBody
                            });
                            if (res.ok) {
                                console.log('[callAIStream] ✅ 重试成功！');
                            }
                        }
                    } catch (retryErr) {
                        console.error('[callAIStream] 重试过程出错:', retryErr.message);
                    }
                }
                
                if (!res.ok) {
                    const errText = await res.text();
                    console.error('[callAIStream] 使用的密钥长度:', currentApiKey.length, '前4字符:', currentApiKey.substring(0, 4) + '...');
                    throw new Error(`API 请求失败: ${res.status} - ${errText.substring(0, 200)}`);
                }
                
                const reader = res.body.getReader();
                
                // ✅ 正确的 SSE 解析方式：使用 \n\n 作为边界
                while (true) {
                    const { done, value } = await reader.read();
                    if (done) break;
                    
                    buffer += decoder.decode(value, { stream: true });
                    
                    let boundary;
                    while ((boundary = buffer.indexOf('\n\n')) !== -1) {
                        const chunk = buffer.slice(0, boundary);
                        buffer = buffer.slice(boundary + 2);
                        
                        if (!chunk.startsWith('data:')) continue;
                        
                        const jsonStr = chunk.replace(/^data:\s*/, '').trim();
                        
                        if (!jsonStr) continue;
                        
                        // ✅ 严格过滤 [DONE]
                        if (jsonStr === '[DONE]' || jsonStr === '[done]') {
                            continue;
                        }
                        
                        let data;
                        try {
                            data = JSON.parse(jsonStr);
                        } catch (e) {
                            console.warn('[callAIStream] Stream JSON parse error:', jsonStr);
                            continue;
                        }
                        
                        const delta = data?.choices?.[0]?.delta?.content;
                        if (!delta) continue;
                        
                        // ✅ 流式阶段：只做字符串拼接，不做任何解析
                        rawText += delta;
                        
                        // ✅ 流式阶段：只更新纯文本显示，不做任何 split / 正则 / markdown
                        // 这里只传递原始文本，让 UI 层只做 textContent 更新
                        if (options.onStreamUpdate) {
                            // 直接传递 rawText，不做任何处理
                            options.onStreamUpdate(rawText);
                        }
                    }
                }
                
                // 处理剩余的 buffer
                if (buffer.trim()) {
                    const jsonStr = buffer.replace(/^data:\s*/, '').trim();
                    if (jsonStr && jsonStr !== '[DONE]' && jsonStr !== '[done]') {
                        try {
                            const data = JSON.parse(jsonStr);
                            const delta = data?.choices?.[0]?.delta?.content;
                            if (delta) {
                                rawText += delta;
                                // 流式阶段：只更新纯文本
                                if (options.onStreamUpdate) {
                                    options.onStreamUpdate(rawText);
                                }
                            }
                        } catch (e) {
                            // 忽略解析错误
                        }
                    }
                }
                
            } catch (err) {
                console.error("[callAIStream] 错误详情:", err);
                throw err;
            }
            
            // ✅ 流结束后，才做处理
            // ✅ 清理末尾的 [DONE] / [done]（防止SSE终止信号泄入内容）
            rawText = rawText.replace(/\s*\[DONE\]\s*$/i, '').trim();
            // 🎯 第二阶段：完成层 - 统一做翻译/结构解析
            const finalText = rawText;
            const processed = processTranslationAndStructure(finalText);
            
            // 🎯 第三阶段：渲染层 - 最后一次性渲染 markdown
            if (options.onComplete) {
                options.onComplete(processed);
            } else {
                // 如果没有提供 onComplete 回调，使用默认的 renderMarkdown
                renderMarkdown(processed);
            }
            
            return processed;
        }
        
        // ✅ 处理翻译和结构拆分（不在流式阶段执行）
        // ⚠️ 重要：这个函数只在流结束后调用，处理完整的文本
        function processTranslationAndStructure(text) {
            if (!text || !text.trim()) return text;
            
            // 🎯 第二阶段：完成层处理
            // 在这里做 split / 正则 / 翻译拆分
            // 流式阶段已经结束，文本是完整的
            
            let processed = text;
            
            // 1. 处理翻译格式（外语（中文翻译））
            // 如果文本包含翻译格式，在这里解析
            // 例如：parseForeignWithTranslation(processed)
            // 但不要在流式阶段拆分，等完整文本后再处理
            
            // 2. 处理结构拆分（如 ||| 分隔符）
            // 如果需要按分隔符拆分，在这里处理
            // 例如：processed.split('|||').map(...)
            
            // 3. 清理和格式化
            // 移除多余的装饰字符、修复格式等
            // processed = processed.replace(/[◇◆★☆●○■□▲△]/g, '');
            
            // 返回处理后的文本
            return processed;
        }
        
        // ✅ 更新流式文本显示（纯文本，不渲染markdown）
        // ⚠️ 重要：这个函数只做纯文本显示，不做任何解析
        // 不做翻译识别、不做正则拆分、不做 markdown 渲染
        function updateStreamingText(text) {
            // ✅ 流式阶段：只更新 textContent，不做任何解析
            // 不做 split、不做正则、不做 markdown、不做翻译识别
            
            // 示例实现：直接更新 DOM 的 textContent（纯文本）
            // const element = document.getElementById('streaming-text');
            // if (element) {
            //     element.textContent = text;  // 只做纯文本更新
            // }
            
            // 调试日志
            console.log('[updateStreamingText] 纯文本更新，长度:', text.length);
        }
        
        // ✅ 渲染最终markdown（在流结束后一次性渲染）
        // ⚠️ 重要：这个函数只在流结束后调用，一次性渲染完整内容
        function renderMarkdown(processedText) {
            // 🎯 第三阶段：渲染层
            // 在流结束后，一次性渲染 markdown
            // 不做流式更新，只做最终渲染
            
            // 示例实现：渲染 markdown 到 DOM
            // const element = document.getElementById('streaming-text');
            // if (element) {
            //     // 使用 markdown 渲染库（如 marked、markdown-it）
            //     element.innerHTML = marked.parse(processedText);
            // }
            
            // 调试日志
            console.log('[renderMarkdown] 最终渲染，长度:', processedText.length);
        }

        // 生成虚拟身份
        async function generateIdentity() {
            const name = document.getElementById('char-name').value;
            const desc = document.getElementById('char-desc').value;
            
            if (!name) {
                alert("请先输入角色名字");
                return;
            }

            const btnText = document.getElementById('gen-btn-text');
            const spinner = document.getElementById('gen-spinner');
            btnText.style.display = 'none';
            spinner.style.display = 'block';

            try {
                const prompt = `你是一个角色卡辅助工具。请根据角色【${name}】的设定（${desc || '暂无详细描述'}），为他/她生成一套虚拟的现代社会身份信息。
请严格返回纯 JSON 格式数据（不要包含 Markdown 代码块标记），包含以下字段：
- account: 虚拟社交账号（英文+数字）
- password: 登录密码（复杂一点）
- phone: 手机号（必须严格为 7 位数字）
- address: 家庭住址（符合角色背景的虚构地址）
- id_card: 身份证号（必须严格为 9 位数字）
- bank_card: 银行卡号（必须严格为 8 位数字）
- bank_password: 银行卡密码（必须严格为 4 位数字）`;

                const content = await callAI([
                    { role: "system", content: "你是一个只输出 JSON 的数据生成助手。" },
                    { role: "user", content: prompt }
                ]);

                const data = extractAndParseJSON(content);
                if (!data) throw new Error("无法解析 AI 返回的 JSON 数据");
                
                // 填入表单
                document.getElementById('char-identity-account').value = data.account || '';
                document.getElementById('char-identity-password').value = data.password || '';
                document.getElementById('char-identity-phone').value = data.phone || '';
                document.getElementById('char-identity-address').value = data.address || '';
                document.getElementById('char-identity-id').value = data.id_card || '';
                document.getElementById('char-identity-bank').value = data.bank_card || '';
                document.getElementById('char-identity-bank-pass').value = data.bank_password || '';

            } catch (err) {
                console.error(err);
                alert("生成失败: " + err.message);
            } finally {
                btnText.style.display = 'inline';
                spinner.style.display = 'none';
            }
        }

        async function deleteCharacter() {
            if (!editingCharId) return;
            if (confirm("确定要删除这个角色吗？")) {
                await db.characters.delete(editingCharId);
                hideCharacterEditor();
                loadCharacterList();
            }
        }

        // 辅助函数：自动导入内嵌的世界书
        async function importCharacterBook(bookData, charName) {
            if (!bookData) return null;
            
            try {
                const bookName = bookData.name || `${charName}的世界书`;
                
                // 存入 lorebooks 表
                const id = await db.lorebooks.add({
                    name: bookName,
                    content: bookData,
                    created_at: Date.now()
                });
                
                return id;
            } catch (e) {
                console.error("导入世界书失败", e);
                return null;
            }
        }

        // 导入角色密码验证
        function requestImportCharacter() {
            // 如果已经验证过，直接打开文件选择
            if (sessionStorage.getItem('import_char_unlocked') === '1') {
                document.getElementById('character-import').click();
                return;
            }
            
            // 创建密码验证弹窗
            const overlay = document.createElement('div');
            overlay.id = 'import-lock-modal';
            overlay.dataset.target = 'character';
            overlay.style.cssText = 'position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.3);display:flex;align-items:center;justify-content:center;z-index:99999;';
            overlay.onclick = (e) => { if (e.target === overlay) overlay.remove(); };
            
            overlay.innerHTML = `
                <div style="background:#fff;border-radius:14px;padding:28px 24px;width:280px;box-shadow:0 8px 30px rgba(0,0,0,0.08);font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
                    <div style="text-align:center;margin-bottom:20px;">
                        <svg viewBox="0 0 24 24" style="width:32px;height:32px;fill:none;stroke:#333;stroke-width:1.5;stroke-linecap:round;stroke-linejoin:round;margin-bottom:8px;"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path></svg>
                        <div style="font-size:15px;font-weight:600;color:#262626;letter-spacing:0.3px;">导入需要验证</div>
                        <div style="font-size:12px;color:#8e8e8e;margin-top:4px;">请输入密码以解锁导入功能</div>
                    </div>
                    <input type="password" id="import-lock-pwd" placeholder="请输入密码" 
                        style="width:100%;padding:12px 14px;border:1px solid #efefef;border-radius:10px;font-size:14px;outline:none;box-sizing:border-box;background:#fafafa;transition:border 0.2s;"
                        onfocus="this.style.borderColor='#333'" onblur="this.style.borderColor='#efefef'">
                    <div id="import-lock-error" style="color:#ff3b30;font-size:12px;margin-top:6px;text-align:center;min-height:16px;"></div>
                    <div style="display:flex;gap:10px;margin-top:14px;">
                        <div onclick="this.closest('#import-lock-modal').remove()" 
                            style="flex:1;text-align:center;padding:11px;border-radius:10px;font-size:14px;color:#8e8e8e;background:#f5f5f5;cursor:pointer;">取消</div>
                        <div onclick="verifyImportPassword()" 
                            style="flex:1;text-align:center;padding:11px;border-radius:10px;font-size:14px;color:#fff;background:#262626;cursor:pointer;font-weight:500;">确认</div>
                    </div>
                </div>
            `;
            
            document.body.appendChild(overlay);
            
            // 自动聚焦 & 回车提交
            setTimeout(() => {
                const pwdInput = document.getElementById('import-lock-pwd');
                if (pwdInput) {
                    pwdInput.focus();
                    pwdInput.addEventListener('keydown', (e) => {
                        if (e.key === 'Enter') verifyImportPassword();
                    });
                }
            }, 100);
        }
        
        function verifyImportPassword() {
            const pwd = document.getElementById('import-lock-pwd').value;
            const modal = document.getElementById('import-lock-modal');
            const target = modal ? modal.dataset.target : 'character';
            
            if (pwd === 'kkk200856') {
                if (target === 'lorebook') {
                    sessionStorage.setItem('import_lorebook_unlocked', '1');
                } else {
                    sessionStorage.setItem('import_char_unlocked', '1');
                }
                if (modal) modal.remove();
                // 验证成功，打开对应的文件选择
                if (target === 'lorebook') {
                    document.getElementById('lorebook-import').click();
                } else {
                    document.getElementById('character-import').click();
                }
            } else {
                const errEl = document.getElementById('import-lock-error');
                if (errEl) errEl.textContent = '密码错误，请重试';
                const pwdInput = document.getElementById('import-lock-pwd');
                if (pwdInput) {
                    pwdInput.value = '';
                    pwdInput.style.borderColor = '#ff3b30';
                    pwdInput.focus();
                    setTimeout(() => { pwdInput.style.borderColor = '#efefef'; }, 1500);
                }
            }
        }

        // 导入角色 (JSON 或 PNG)
        function importCharacterFile(input) {
            const file = input.files[0];
            if (!file) return;
            
            if (file.type.includes('image') || file.name.endsWith('.png')) {
                // 处理 PNG
                const reader = new FileReader();
                reader.onload = async (e) => {
                    try {
                        // 1. 先尝试当做图片读取显示
                        const avatarBase64 = e.target.result;
                        
                        // 2. 解析 PNG 元数据中的 JSON
                        const arrayBuffer = await file.arrayBuffer();
                        const jsonStr = extractPngText(new Uint8Array(arrayBuffer));
                        
                        if (!jsonStr) {
                            alert("未在这张图片中找到角色数据 (tEXt chunk)");
                            createNewCharacter();
                            document.getElementById('char-avatar-preview').style.backgroundImage = `url(${avatarBase64})`;
                            document.getElementById('char-avatar-placeholder').style.display = 'none';
                            input.value = '';
                            return;
                        }
                        
                        const json = JSON.parse(jsonStr);
                        // 处理不同格式 (TavernAI V1/V2)
                        let charData = {};
                        if (json.data) {
                            // V2 spec
                            charData = json.data;
                        } else {
                            // V1 或直接结构
                            charData = json;
                        }
                        
                        // 尝试导入世界书
                        let lorebookId = null;
                        if (charData.character_book) {
                             lorebookId = await importCharacterBook(charData.character_book, charData.name);
                        }
                        
                        // 存入 DB
                        await db.characters.add({
                            name: charData.name || '未命名',
                            nick: charData.nickname || '', 
                            description: charData.description || charData.personality || '', 
                            type: currentCharacterType, 
                            avatar: avatarBase64,
                            original_data: json,
                            lorebookIds: lorebookId ? [lorebookId] : null, // 关联世界书ID数组
                            lorebookId: lorebookId, // 兼容字段
                            updated_at: Date.now()
                        });
                        
                        let msg = `✅ 成功导入角色: ${charData.name}`;
                        if (lorebookId) msg += `\n📚 并自动导入了世界书`;
                        alert(msg);
                        loadCharacterList();
                        
                    } catch (err) {
                        console.error(err);
                        alert("解析 PNG 失败: " + err.message);
                    }
                };
                reader.readAsDataURL(file);
                
            } else {
                // 处理 JSON
                const reader = new FileReader();
                reader.onload = async (e) => {
                    try {
                        const json = JSON.parse(e.target.result);
                        // 兼容性处理
                        let charData = json;
                        if (json.data) charData = json.data; // Spec V2
                        
                        // 尝试导入世界书
                        let lorebookId = null;
                        if (charData.character_book) {
                             lorebookId = await importCharacterBook(charData.character_book, charData.name);
                        }
                        
                        await db.characters.add({
                            name: charData.name || '未命名',
                            nick: charData.nickname || '',
                            description: charData.description || charData.personality || '',
                            type: currentCharacterType,
                            avatar: '', 
                            original_data: json,
                            lorebookId: lorebookId, // 关联世界书ID
                            updated_at: Date.now()
                        });
                        
                        let msg = `✅ 成功导入角色: ${charData.name}`;
                        if (lorebookId) msg += `\n📚 并自动导入了世界书`;
                        alert(msg);
                        loadCharacterList();
                    } catch (err) {
                        alert("JSON 解析失败: " + err.message);
                    }
                };
                reader.readAsText(file);
            }
            input.value = '';
        }

        // 简易 PNG tEXt 提取器 (修复中文乱码版)
        function extractPngText(uint8Array) {
            // PNG Header: 89 50 4E 47 0D 0A 1A 0A
            let offset = 8;
            const textDecoder = new TextDecoder();
            
            while (offset < uint8Array.length) {
                // 读取 Chunk Length (4 bytes, Big Endian)
                const length = (uint8Array[offset] << 24) | (uint8Array[offset+1] << 16) | (uint8Array[offset+2] << 8) | uint8Array[offset+3];
                offset += 4;
                
                // 读取 Chunk Type (4 bytes)
                const type = String.fromCharCode(...uint8Array.slice(offset, offset + 4));
                offset += 4;
                
                if (type === 'tEXt') {
                    const data = uint8Array.slice(offset, offset + length);
                    // tEXt 格式: Keyword + null separator + Text string
                    // 查找 null separator (0x00)
                    let nullIndex = -1;
                    for (let i = 0; i < length; i++) {
                        if (data[i] === 0) {
                            nullIndex = i;
                            break;
                        }
                    }
                    
                    if (nullIndex > -1) {
                        const keyword = textDecoder.decode(data.slice(0, nullIndex));
                        const textBytes = data.slice(nullIndex + 1);
                        const text = textDecoder.decode(textBytes);
                        
                        if (keyword === 'chara') {
                            // TavernAI 格式通常是 Base64 编码的 JSON
                            try {
                                // 修复乱码的关键步骤：
                                // 1. atob 解码 base64 -> binary string
                                const binaryString = atob(text);
                                // 2. binary string -> Uint8Array
                                const bytes = new Uint8Array(binaryString.length);
                                for (let i = 0; i < binaryString.length; i++) {
                                    bytes[i] = binaryString.charCodeAt(i);
                                }
                                // 3. TextDecoder 解码 utf-8
                                const decoded = new TextDecoder('utf-8').decode(bytes);
                                return decoded;
                            } catch (e) {
                                // 也许不是 Base64，或者解码失败，直接返回原始文本
                                return text;
                            }
                        }
                    }
                }
                
                // 跳过 Data 和 CRC (4 bytes)
                offset += length + 4;
                
                if (type === 'IEND') break;
            }
            return null;
        }